# This file intentionally left blank
BOOTLOADER = rp2040
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes
NKRO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
